ENV['COCOAPODS_DISABLE_STATS'] = 'true'

target 'normal_demo' do
  use_frameworks!
  use_modular_headers!

  pod 'NativePod', :path => 'NativePod'
  pod 'shared_preferences', :path => 'shared_preferences'
  pod 'Flutter', :path => 'Flutter'
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
   end
end
